### ISSUE TITLE
CREAM error: chromosome with low number of regions and you may get error

### ISSUE THREAD

**Issue by venuthatikonda** [bhklab/CREAM#6]
Hi,

recently I came across this tool and wanted to give it a try. When I used a bed file it gave the following error

```
Error in quantile.default(bb) :
  missing values and NaN's not allowed if 'na.rm' is FALSE
In addition: Warning messages:
1: In CREAM(in_path = "my_70percent_overlap.bed", out_path = "./my_70percent_overlap_CORES_CREAM.bed",  :
  There are chromosome with low number of regions and you may get error. The reason is that highest Order may become larger than the number of regions in a chromosome. Hence, there will not be enough regions in that chromosome for clustering.
2: In log(SortedWindow_Vec[-RemovePeaks]) : NaNs produced
```

How would you suggest to deal with it?

Thank you.

**Comment by alimadani** [comment]
Hi,

Could you provide me the number of regions you have per chromosome? Also please let me know if you have any overlap between your regions.

**Comment by alimadani** [comment]
Hi,

Could you provide me the number of regions you have per chromosome? Also please let me know if you have any overlap between your regions.
