### ISSUE TITLE
input issue

### ISSUE THREAD

**Issue by JulieHoang** [bhklab/CREAM#8]
I tried to use CREAM with output from Genrich (narrowPeaks) format. I run into this error and unsure how to proceed. Would you mind helping me?
#CREAMfunction
IdentifiedCOREs <- CREAM(in_path=system.file("extdata", "816_775.narrowPeaks.bed", package = "CREAM"), MinLength = 1000, peakNumMin = 2 )
Error in read.table(in_path, sep = "\t") : no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

**Comment by alimadani** [comment]
Are you sure that your file is tab delimited?

**Comment by JulieHoang** [comment]
Hi, yes. My file is tab-delim
Issue is fixed now.

**Comment by merihdeniz19** [comment]
I also have the same problem. My file is tab delimited. I would be very grateful if you could help me with this issue!

**Comment by alimadani** [comment]
Merih, the input is assumed to be tab delimited. CREAM uses read.table() to read your file(s). Could you copy the error and the first few lines of your file here?

**Comment by merihdeniz19** [comment]
Thank you so much for your prompt reply. 

The error message is:
Error in read.table(in_path, sep = "\t") : no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

And the first few lines of my file is:
”V1”	”V2”	"V3"	
”Stem_H3K27Ac_hg38_i82_bam_peak_1”	”chr1 ”	12161	14474
”Stem_H3K27Ac_hg38_i82_bam_peak_2”	”chr1”	14629	14832
”Stem_H3K27Ac_hg38_i82_bam_peak_3”	”chr1”	28730	29809
”Stem_H3K27Ac_hg38_i82_bam_peak_4”	”chr1”	137069	137385
”Stem_H3K27Ac_hg38_i82_bam_peak_5”	”chr1”	182849	184938
”Stem_H3K27Ac_hg38_i82_bam_peak_6”	”chr1”	191414	191628
”Stem_H3K27Ac_hg38_i82_bam_peak_7”	”chr1”	199178	200345
”Stem_H3K27Ac_hg38_i82_bam_peak_8”	”chr1”	258698	258938
”Stem_H3K27Ac_hg38_i82_bam_peak_9”	”chr1”	376880	377261
”Stem_H3K27Ac_hg38_i82_bam_peak_10”	”chr1”	394328	394524

**Comment by alimadani** [comment]
It seems that they are not bed files. Remove the rownames and save the files as bed and CREAM should run OK.

**Comment by merihdeniz19** [comment]
Thank you so much for your reply!
I tried deleting the row names and saving the file as bed (it has a bed extension), but I'm still getting the same error. 

Now the file looks like:
"V1"	"V2"	"V3"
chr1	12161	14474
chr1	14629	14832
chr1	28730	29809
chr1	137069	137385
chr1	182849	184938
chr1	191414	191628

**Comment by alimadani** [comment]
could you copy the command you run in R? (The exact command with all the specified parameters)

**Comment by merihdeniz19** [comment]
Yes of course! Thanks a lot!

CREAM(system.file("extdata", "STEM1_CREAM3.bed", package = "CREAM"), MinLength = 1000, peakNumMin = 2)
