### ISSUE TITLE
Nothing pointing to WindowSizeRecog_freecutoff?

### ISSUE THREAD

**Issue by reskejak** [bhklab/CREAM#9]
I have been trying to implement LOCKs using this repository and your codeocean link from your recent paper (https://codeocean.com/capsule/6911149/tree/v1).

I understand that the CREAM_Cutoff is the iterative optimization of WScutoff. The new CREAM parameter optimize=TRUE evokes ElementRecog_freecutoff instead of ElementRecog. However, there is also a WindowSizeRecog_freecutoff, but I do not see any scripts evoking it. Was this not implemented in the final version of the CREAM update?

**Comment by alimadani** [comment]
Sorry, the version was not updated. The updated version is pushed. Please try it out and open another issue if you find any problem.
